# We're using the latest version of Prefect with Python 3.10
FROM prefecthq/prefect:2-python3.11

# Install pipenv
RUN pip install pipenv

# Set working directory
WORKDIR /app

# Copy Pipfile and Pipfile.lock
COPY Pipfile Pipfile.lock /app/

# Install dependencies
RUN pipenv install --system --deploy

# Copy the setup script
COPY prefect.yaml /app/
COPY src /app/src/
COPY data /app/data/

# Expose port 4200 for Prefect
EXPOSE 4200

# Make the script executable
#RUN chmod +x /app/training.sh

# Command to start Prefect server and run setup script
CMD ["sh", "-c", "\
  prefect server start --host 0.0.0.0 & \
  sleep 10 && \
  (prefect work-pool inspect zoompool || prefect work-pool create --type process zoompool) && \
  prefect deploy src/hyperopt_register_model.py:main_flow -n train-heart-attack-model -p zoompool && \
  prefect deploy src/monitor.py:main_flow -n monitor-heart-attack-data-drift -p zoompool && \
  prefect worker start --pool 'zoompool' \
"]